-- VehCatalog auto-generated (last session only)
return {
    ["abrams"] = {"abrams",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/abrams_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["abramsb"] = {"abramsb",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/abramsb_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak200"] = {"blak200",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak200_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak200b"] = {"blak200b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak200b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak501"] = {"blak501",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak501_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak501b"] = {"blak501b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak501b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak502"] = {"blak502",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak502_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak502b"] = {"blak502b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak502b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak503"] = {"blak503",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak503_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak503b"] = {"blak503b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak503b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak504"] = {"blak504",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak504_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak504b"] = {"blak504b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak504b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak702"] = {"blak702",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak702_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak702b"] = {"blak702b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak702b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak703"] = {"blak703",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak703_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak703b"] = {"blak703b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak703b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak707"] = {"blak707",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak707_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak707b"] = {"blak707b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak707b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak708"] = {"blak708",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak708_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak708b"] = {"blak708b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak708b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak709"] = {"blak709",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak709_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak709b"] = {"blak709b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak709b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak710"] = {"blak710",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak710_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak710b"] = {"blak710b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak710b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak711"] = {"blak711",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak711_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak711b"] = {"blak711b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak711b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak712"] = {"blak712",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak712_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak712b"] = {"blak712b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak712b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak713"] = {"blak713",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak713_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak713b"] = {"blak713b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak713b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak714"] = {"blak714",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak714_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak714b"] = {"blak714b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak714b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak715"] = {"blak715",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak715_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["blak715b"] = {"blak715b",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/blak715b_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
}