-- VehCatalog auto-generated (last session only)
return {
    ["isforces1"] = {"isforces1",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces1_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces10"] = {"isforces10",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces10_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces12"] = {"isforces12",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces12_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces13"] = {"isforces13",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces13_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces14"] = {"isforces14",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces14_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces15"] = {"isforces15",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces15_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces16"] = {"isforces16",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces16_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces2"] = {"isforces2",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces2_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces3"] = {"isforces3",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces3_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces4"] = {"isforces4",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces4_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces5"] = {"isforces5",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces5_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces6"] = {"isforces6",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces6_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces7"] = {"isforces7",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces7_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces8"] = {"isforces8",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces8_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isforces9"] = {"isforces9",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isforces9_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["ishtar2g"] = {"ishtar2g",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/ishtar2g_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat1"] = {"isswat1",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat1_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat10"] = {"isswat10",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat10_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat11"] = {"isswat11",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat11_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat12"] = {"isswat12",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat12_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat13"] = {"isswat13",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat13_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat14"] = {"isswat14",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat14_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat2"] = {"isswat2",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat2_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat3"] = {"isswat3",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat3_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat4"] = {"isswat4",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat4_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat5"] = {"isswat5",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat5_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat6"] = {"isswat6",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat6_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat7"] = {"isswat7",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat7_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat8"] = {"isswat8",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat8_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isswat9"] = {"isswat9",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isswat9_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["nissan25df"] = {"nissan25df",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/nissan25df_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["sitra945"] = {"sitra945",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/sitra945_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
}