-- VehCatalog auto-generated (last session only)
return {
    ["CID1"] = {"CID1",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID1_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID10"] = {"CID10",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID10_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID11"] = {"CID11",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID11_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID2"] = {"CID2",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID2_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID3"] = {"CID3",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID3_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID4"] = {"CID4",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID4_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID5"] = {"CID5",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID5_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID6"] = {"CID6",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID6_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID7"] = {"CID7",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID7_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID8"] = {"CID8",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID8_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["CID9"] = {"CID9",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/CID9_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["isfbi6"] = {"isfbi6",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/isfbi6_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["lek911"] = {"lek911",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/lek911_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra900"] = {"tra900",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra900_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra901"] = {"tra901",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra901_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra902"] = {"tra902",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra902_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra903"] = {"tra903",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra903_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra904"] = {"tra904",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra904_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra905"] = {"tra905",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra905_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra907"] = {"tra907",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra907_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra909"] = {"tra909",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra909_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra910"] = {"tra910",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra910_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra911"] = {"tra911",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra911_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra913"] = {"tra913",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra913_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra914"] = {"tra914",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra914_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra915"] = {"tra915",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra915_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra916"] = {"tra916",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra916_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra917"] = {"tra917",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra917_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra918"] = {"tra918",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra918_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra919"] = {"tra919",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra919_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
    ["tra920"] = {"tra920",0,"<img src='https://raw.githubusercontent.com/abomayar90/carsfivem/main/tra920_custom_setup.png' /><br/><br/>Top Speed: 0 KM/h<br/>"},
}